spring:
  application:
  name: AnketaAppKotlin
  datasource:
    url: 'jdbc:postgresql://dpg-co4tqvn79t8c7397fgl0-a.frankfurt-postgres.render.com/data_wol'
    username: 'wolahi'
    password: 'Oun8OZFvDgjNS7fOt2Qlmu3ybMEVL7AM'
  exposed:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
jwt-security:
  secret: 'dASDASdsadasdsadhjksahdbksjahdkjlshakDJHsakjhdJKALhdksajhdlKJSAHdkjhASLJKDha'
  expirationTime: 600 #minutes
  expirationTimeRefresh: 6000 #minutes
  expirationTimeTemporary: 5 #minutes
