spring:
  application:
  name: AnketaAppKotlin
  datasource:
    url: 'jdbc:postgresql://localhost/anketa_db'
    username: 'postgres'
    password: '1234'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
jwt-security:
  secret: 'dASDASdsadasdsadhjksahdbksjahdkjlshakDJHsakjhdJKALhdksajhdlKJSAHdkjhASLJKDha'
  expirationTime: 600 #minutes
  expirationTimeRefresh: 6000 #minutes
  expirationTimeTemporary: 5 #minutes
